"""
Networking sandbox — you're SSH'd into app-1 (10.0.1.10) on a small modelled
network, and things that should connect don't. Every connection is worked
out layer by layer, the way a real packet's fate is: name resolution
(/etc/hosts first, then the DNS server in /etc/resolv.conf), the route
(local subnet or the default gateway), ARP for the next hop, the local
firewall, whether anything listens on the far end, and finally the MTU.
So each layer fails with its own real symptom: 'Temporary failure in name
resolution', 'No route to host', a timeout, 'Connection refused', or a
transfer that starts and then hangs.

Two of five problems are seeded:
  wrong_gateway      the default route points at 10.0.1.254, which doesn't exist
  dead_dns           resolv.conf names a DNS server that was decommissioned
  stale_hosts        /etc/hosts pins api.shop.example to the API's old address
  firewall_blocks_db a leftover OUTPUT rule drops traffic to PostgreSQL
  jumbo_mtu          eth0 was set to MTU 9000 on a 1500-byte network

Nothing here sends a real packet.
"""

import ipaddress
import random
import shlex

from sandbox_common import render_table, run_loop

PROBLEMS = ["wrong_gateway", "dead_dns", "stale_hosts", "firewall_blocks_db", "jumbo_mtu"]

REPORTS = {
    "wrong_gateway": "app-1 can't reach anything outside its own subnet: not the API, not the package mirror.",
    "dead_dns": "Everything on app-1 that uses a hostname fails, though some things work by IP.",
    "stale_hosts": "The app on app-1 times out calling api.shop.example, but the API team says it's healthy "
                   "and DNS is correct.",
    "firewall_blocks_db": "The app on app-1 can't reach its database since last night's hardening work.",
    "jumbo_mtu": "Health checks from app-1 pass, but big responses (the product catalogue, package downloads) "
                 "hang forever.",
}

MY_IP, MY_NET = "10.0.1.10", "10.0.1.0/24"
GOOD_GW, BAD_GW = "10.0.1.1", "10.0.1.254"
GOOD_DNS, DEAD_DNS = "10.0.1.2", "10.0.0.53"
API_IP, OLD_API_IP = "10.0.2.15", "10.0.2.40"
PATH_MTU = 1500

# Every machine that answers, and the TCP/UDP ports it serves.
HOSTS = {
    GOOD_GW: {"name": "gw-1", "ports": set()},
    GOOD_DNS: {"name": "dns-1", "ports": {53}},
    "10.0.1.20": {"name": "db-1", "ports": {5432, 22}},
    API_IP: {"name": "api-1", "ports": {443, 80, 22}},
    "203.0.113.80": {"name": "mirror", "ports": {443, 80}},
}
DNS_RECORDS = {
    "api.shop.example": API_IP,
    "db-1.shop.internal": "10.0.1.20",
    "dns-1.shop.internal": GOOD_DNS,
    "gw-1.shop.internal": GOOD_GW,
    "packages.example.org": "203.0.113.80",
}
MACS = {GOOD_GW: "52:54:00:1a:2b:01", GOOD_DNS: "52:54:00:1a:2b:02", "10.0.1.20": "52:54:00:1a:2b:20"}

HELP_TEXT = """Supported commands (a modelled network; no real packets are sent):
  ip addr | ip route | ip route get <ip> | ip link | ip neigh
  cat /etc/resolv.conf | /etc/hosts | /etc/nsswitch.conf
  getent hosts <name>   dig <name> [@server] [+short]   nslookup <name>
  help | exit          (pipes work: ip route | grep default)"""


def _hosts_file(stale: bool) -> list:
    lines = ["127.0.0.1\tlocalhost", f"{MY_IP}\tapp-1.shop.internal app-1", "",
             "# The following lines are desirable for IPv6 capable hosts",
             "::1\tip6-localhost ip6-loopback"]
    if stale:
        lines += ["", "# temporary: pin the API during the March migration (dana)", f"{OLD_API_IP}\tapi.shop.example"]
    return lines


def generate_state(seed=None, problems=None) -> dict:
    """Random 2 problems by default; mystery incidents pass an explicit list."""
    rng = random.Random(seed)
    problems = list(problems) if problems is not None else rng.sample(PROBLEMS, k=2)
    firewall = {
        "INPUT": [{"target": "ACCEPT", "proto": "tcp", "dport": 22, "dest": "0.0.0.0/0", "comment": "ssh"},
                  {"target": "ACCEPT", "proto": "tcp", "dport": 8080, "dest": "0.0.0.0/0", "comment": "app"}],
        "OUTPUT": [],
    }
    if "firewall_blocks_db" in problems:
        firewall["OUTPUT"] = [
            {"target": "ACCEPT", "proto": "tcp", "dport": 443, "dest": "0.0.0.0/0", "comment": "https out"},
            {"target": "DROP", "proto": "tcp", "dport": 5432, "dest": "10.0.1.0/24",
             "comment": "CIS 3.5 test - remove after review"},
        ]
    state = {
        "seed": seed,
        "problems": problems,
        "link": {"name": "eth0", "up": True, "mtu": 9000 if "jumbo_mtu" in problems else 1500,
                 "mac": "52:54:00:1a:2b:10", "addr": f"{MY_IP}/24"},
        "default_gw": BAD_GW if "wrong_gateway" in problems else GOOD_GW,
        "files": {
            "/etc/resolv.conf": ["# Generated by the provisioning script; edit with care",
                                 f"nameserver {DEAD_DNS if 'dead_dns' in problems else GOOD_DNS}",
                                 "search shop.internal"],
            "/etc/hosts": _hosts_file("stale_hosts" in problems),
            "/etc/nsswitch.conf": ["passwd:         files", "group:          files",
                                   "hosts:          files dns", "networks:       files"],
        },
        "firewall": firewall,
    }
    state["baseline"] = {"addr": state["link"]["addr"], "input_rules": len(firewall["INPUT"])}
    return state


# ------------------------------------------------------------ the network

def _nameserver(state: dict):
    for line in state["files"]["/etc/resolv.conf"]:
        parts = line.split()
        if len(parts) >= 2 and parts[0] == "nameserver":
            return parts[1]
    return None


def _hosts_lookup(state: dict, name: str):
    for line in state["files"]["/etc/hosts"]:
        parts = line.split("#", 1)[0].split()
        if len(parts) >= 2 and name in parts[1:]:
            return parts[0]
    return None


def _is_ip(text: str) -> bool:
    try:
        ipaddress.ip_address(text)
        return True
    except ValueError:
        return False


def _local(ip: str) -> bool:
    return ipaddress.ip_address(ip) in ipaddress.ip_network(MY_NET)


def next_hop(state: dict, ip: str):
    """(hop, error): the address we must ARP for, or why there's none."""
    if not state["link"]["up"]:
        return None, "Network is unreachable"
    if _local(ip):
        return ip, None
    if state["default_gw"] is None:
        return None, "Network is unreachable"
    return state["default_gw"], None


def arp_ok(hop: str) -> bool:
    return hop in HOSTS


def dns_query(state: dict, name: str, server=None):
    """(ip or None, error or None) as a DNS client sees it, ignoring /etc/hosts."""
    server = server or _nameserver(state)
    if server is None:
        return None, "no servers could be reached"
    hop, err = next_hop(state, server)
    if err or not arp_ok(hop) or server not in HOSTS or 53 not in HOSTS[server]["ports"]:
        return None, "timed out"
    fqdn = name if name in DNS_RECORDS else f"{name}.shop.internal"
    if fqdn in DNS_RECORDS:
        return DNS_RECORDS[fqdn], None
    return None, "NXDOMAIN"


def resolve(state: dict, name: str):
    """(ip, error) the way most programs resolve: nsswitch 'files dns'."""
    if _is_ip(name):
        return name, None
    pinned = _hosts_lookup(state, name)
    if pinned:
        return pinned, None
    ip, err = dns_query(state, name)
    if ip:
        return ip, None
    return None, "Temporary failure in name resolution" if err == "timed out" else "Name or service not known"


# -------------------------------------------------------------------- views

def _ip(state: dict, args: list) -> str:
    obj = args[0] if args else ""
    link = state["link"]
    if obj in ("a", "addr", "address"):
        flags = "BROADCAST,MULTICAST,UP,LOWER_UP" if link["up"] else "BROADCAST,MULTICAST"
        oper = "UP" if link["up"] else "DOWN"
        return "\n".join([
            "1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000",
            "    inet 127.0.0.1/8 scope host lo",
            f"2: eth0: <{flags}> mtu {link['mtu']} qdisc fq_codel state {oper} group default qlen 1000",
            f"    link/ether {link['mac']} brd ff:ff:ff:ff:ff:ff",
            f"    inet {link['addr']} brd 10.0.1.255 scope global eth0"])
    if obj in ("l", "link"):
        oper = "UP" if link["up"] else "DOWN"
        return "\n".join([
            "1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT",
            f"2: eth0: <BROADCAST,MULTICAST{',UP,LOWER_UP' if link['up'] else ''}> mtu {link['mtu']} "
            f"qdisc fq_codel state {oper} mode DEFAULT",
            f"    link/ether {link['mac']} brd ff:ff:ff:ff:ff:ff"])
    if obj in ("r", "route", "ro"):
        if len(args) >= 3 and args[1] == "get":
            target = args[2]
            if not _is_ip(target):
                return f'Error: any valid prefix is expected rather than "{target}".'
            hop, err = next_hop(state, target)
            if err:
                return f"RTNETLINK answers: {err}"
            via = "" if hop == target else f" via {hop}"
            return f"{target}{via} dev eth0 src {MY_IP} uid 0\n    cache"
        lines = []
        if state["default_gw"] and state["link"]["up"]:
            lines.append(f"default via {state['default_gw']} dev eth0 proto static")
        if state["link"]["up"]:
            lines.append(f"{MY_NET} dev eth0 proto kernel scope link src {MY_IP}")
        return "\n".join(lines)
    if obj in ("n", "neigh", "neighbor", "neighbour"):
        rows = []
        for hop in sorted({state["default_gw"], GOOD_DNS, "10.0.1.20"} - {None}):
            if arp_ok(hop):
                rows.append(f"{hop} dev eth0 lladdr {MACS.get(hop, '52:54:00:1a:2b:99')} REACHABLE")
            else:
                rows.append(f"{hop} dev eth0 FAILED")
        return "\n".join(rows)
    return f"ip {obj}: not simulated in the sandbox. Type 'help' for supported commands."


def _getent(state: dict, args: list) -> str:
    if len(args) < 2 or args[0] != "hosts":
        return "getent: the sandbox supports: getent hosts <name>"
    ip, _ = resolve(state, args[1])
    return f"{ip:<15} {args[1]}" if ip else ""


def _dig(state: dict, args: list) -> str:
    server = next((a[1:] for a in args if a.startswith("@")), None)
    short = "+short" in args
    names = [a for a in args if not a.startswith(("@", "+", "-"))]
    if not names:
        return "dig: name required"
    name = names[0]
    used = server or _nameserver(state)
    ip, err = dns_query(state, name, server)
    if err == "timed out":
        return f";; communications error to {used}#53: timed out\n" * 2 + \
            f";; no servers could be reached"
    if short:
        return ip or ""
    status = "NOERROR" if ip else "NXDOMAIN"
    lines = [f"; <<>> DiG 9.18.28 <<>> {name}", ";; global options: +cmd", ";; Got answer:",
             f";; ->>HEADER<<- opcode: QUERY, status: {status}, id: 41204", "",
             ";; QUESTION SECTION:", f";{name}.\t\t\tIN\tA", ""]
    if ip:
        lines += [";; ANSWER SECTION:", f"{name}.\t\t300\tIN\tA\t{ip}", ""]
    lines += [";; Query time: 1 msec", f";; SERVER: {used}#53({used}) (UDP)"]
    return "\n".join(lines)


def _nslookup(state: dict, args: list) -> str:
    if not args:
        return "nslookup: name required"
    used = _nameserver(state)
    ip, err = dns_query(state, args[0])
    if err == "timed out":
        return f";; communications error to {used}#53: timed out\n;; no servers could be reached"
    head = f"Server:\t\t{used}\nAddress:\t{used}#53\n\n"
    if not ip:
        return head + f"** server can't find {args[0]}: NXDOMAIN"
    return head + f"Name:\t{args[0]}\nAddress: {ip}"


def handle_command(state: dict, raw: str) -> str:
    try:
        tokens = shlex.split(raw)
    except ValueError as e:
        return f"parse error: {e}"
    if not tokens:
        return ""
    cmd, args = tokens[0], tokens[1:]
    if cmd == "sudo" and args:
        cmd, args = args[0], args[1:]
    if cmd in ("help", "?"):
        return HELP_TEXT
    if cmd == "ip":
        return _ip(state, args)
    if cmd == "cat":
        missing = [f for f in args if f not in state["files"]]
        if missing:
            return f"cat: {missing[0]}: No such file or directory"
        return "\n".join("\n".join(state["files"][f]) for f in args)
    if cmd == "getent":
        return _getent(state, args)
    if cmd == "dig":
        return _dig(state, args)
    if cmd == "nslookup":
        return _nslookup(state, args)
    return f"{cmd}: not simulated in the sandbox. Type 'help' for supported commands."


def describe_state(state: dict) -> list:
    return ["You're SSH'd into app-1 (10.0.1.10), an application server. Reported:",
            *[f"  - {REPORTS[p]}" for p in state["problems"]],
            "Find each cause and fix it from app-1. You're connected over eth0: careful with it."]


def run_sandbox() -> None:
    run_loop("net", "network", generate_state, handle_command, describe_state)
